[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/assets/**"]

[functions.generator]
  included_files = ["netlify/functions/assets/**", "node_modules/puppeteer/.local-chromium/**"]
  external_node_modules = ["puppeteer"]
  node_bundler = "esbuild"
  timeout = 60