[build]
  command = "npm install && npm run build && npm run postinstall"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/assets/**", ".cache/puppeteer/**"]

[functions.generator]
  included_files = ["netlify/functions/assets/**", "node_modules/puppeteer/.local-chromium/**"]
  external_node_modules = ["puppeteer-core", "puppeteer"]
  node_bundler = "esbuild"
  timeout = 60
